const FoodLists = [
  {
    id: 1,
    image: "./images/b1.jpg",
    name: "Break-1",
    category: "breakfast",
    price: "$100",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
  },
  {
    id: 2,
    image: "./images/b2.jpg",
    name: "Break-2",
    category: "breakfast",
    price: "$100",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
  },
  {
    id: 3,
    image: "./images/b3.jpg",
    name: "Break-3",
    category: "breakfast",
    price: "$100",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
  },
  {
    id: 4,
    image: "./images/l1.jpg",
    name: "Lunch-1",
    category: "lunch",
    price: "$100",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
  },
  {
    id: 5,
    image: "./images/l2.jpg",
    name: "Lunch-2",
    category: "lunch",
    price: "$100",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
  },
  {
    id: 6,
    image: "./images/l3.jpg",
    name: "Lunch-3",
    category: "lunch",
    price: "$100",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
  },
  {
    id: 7,
    image: "./images/d1.jpg",
    name: "Dinner-1",
    category: "dinner",
    price: "$100",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
  },
  {
    id: 8,
    image: "./images/d2.jpg",
    name: "Dinner-2",
    category: "dinner",
    price: "$100",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
  },
  {
    id: 9,
    image: "./images/d3.jpg",
    name: "Dinner-3",
    category: "dinner",
    price: "$100",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
  },
];

export default FoodLists;
